# -*- coding: utf-8 -*-
"""
Language mappings for French, Spanish, Russian, Vietnamese, Mongolian, Arabic, Thai, Indonesian
for all 232 Korean Basic Dictionary category components.
"""

FR_MAP = {
  "가사 행위": "Tâches ménagères",
  "가족 행사": "Événements familiaux",
  "가족 행사-명절": "Fêtes et célébrations familiales",
  "감각": "Sens et sensations",
  "감사하기": "Exprimer sa gratitude",
  "감정": "Émotions",
  "감정, 기분 표현하기": "Exprimer ses émotions et son humeur",
  "개념": "Concepts",
  "개인 정보 교환하기": "Échanger des informations personnelles",
  "건강": "Santé",
  "건물 종류": "Types de bâtiments",
  "건축": "Architecture",
  "경제 산물": "Produits économiques",
  "경제 상태": "Conditions économiques",
  "경제 생활": "Vie économique",
  "경제 수단": "Moyens économiques",
  "경제 행위": "Activités économiques",
  "경제 행위 장소": "Lieux d'activités économiques",
  "경제 행위 주체": "Acteurs économiques",
  "경제·경영": "Économie et gestion",
  "곡류": "Céréales et grains",
  "곤충류": "Insectes",
  "공공 기관": "Institutions publiques",
  "공공 기관 이용하기(도서관)": "Utiliser les services publics (Bibliothèque)",
  "공공 기관 이용하기(우체국)": "Utiliser les services publics (Poste)",
  "공공 기관 이용하기(출입국 관리 사무소)": "Utiliser les services publics (Immigration)",
  "공공기관 이용하기": "Utiliser les institutions publiques",
  "공연과 감상": "Spectacles et appréciation",
  "과일": "Fruits",
  "과학": "Science",
  "과학 및 기술": "Science et technologie",
  "과학과 기술": "Sciences et technologies",
  "교수 학습 주체": "Participants à l'enseignement et à l'apprentissage",
  "교수 학습 행위": "Activités d'enseignement et d'apprentissage",
  "교육": "Éducation",
  "교육 기관": "Établissements d'enseignement",
  "교통 수단": "Moyens de transport",
  "교통 이용 장소": "Lieux de transport",
  "교통 이용 행위": "Utilisation des transports",
  "교통 이용하기": "Prendre les transports",
  "기상 및 기후": "Météo et climat",
  "기후": "Climat",
  "길찾기": "Trouver son chemin",
  "날씨와 계절": "Météo et saisons",
  "날짜 표현하기": "Exprimer la date",
  "능력": "Aptitudes et capacités",
  "대중 매체": "Médias de masse",
  "대중 문화": "Culture populaire",
  "동물 소리": "Cris d'animaux",
  "동물류": "Animaux",
  "동물의 부분": "Parties d'animaux",
  "동식물": "Faune et flore",
  "동식물 행위": "Comportements de la faune et de la flore",
  "말": "Parole et langage",
  "맛": "Goûts et saveurs",
  "매체": "Médias",
  "모양": "Formes et aspects",
  "모자, 신발, 장신구": "Chapeaux, chaussures et accessoires",
  "무기": "Armes",
  "문제 해결하기(분실 및 고장)": "Résoudre un problème (Perte et panne)",
  "문학": "Littérature",
  "문화": "Culture",
  "문화 비교하기": "Comparer les cultures",
  "문화 생활 장소": "Lieux de vie culturelle",
  "문화 차이": "Différences culturelles",
  "문화 활동": "Activités culturelles",
  "문화 활동 주체": "Acteurs des activités culturelles",
  "물건 사기": "Faire des achats",
  "미술": "Beaux-arts",
  "미용 행위": "Soins de beauté et coiffure",
  "밝기": "Luminosité",
  "법": "Droit et justice",
  "병과 증상": "Maladies et symptômes",
  "병원 이용하기": "Aller à l'hôpital",
  "보건과 의료": "Santé et soins médicaux",
  "복장 표현하기": "Décrire la tenue vestimentaire",
  "빈도": "Fréquence",
  "사건, 사고, 재해 기술하기": "Décrire des incidents, accidents et catastrophes",
  "사과하기": "Présenter des excuses",
  "사람의 종류": "Types de personnes",
  "사법 및 치안 주체": "Acteurs de la justice et de l'ordre public",
  "사법 및 치안 행위": "Actions judiciaires et de maintien de l'ordre",
  "사회 문제": "Problèmes de société",
  "사회 생활": "Vie en société",
  "사회 생활 상태": "Conditions de vie sociale",
  "사회 제도": "Systèmes sociaux",
  "사회 행사": "Événements sociaux",
  "사회 활동": "Activités sociales",
  "삶": "Vie et existence",
  "삶의 상태": "États de la vie",
  "삶의 행위": "Actes de la vie",
  "색깔": "Couleurs",
  "생리 현상": "Phénomènes physiologiques",
  "생활 용품": "Articles du quotidien",
  "성격": "Personnalité",
  "성격 표현하기": "Décrire la personnalité",
  "성질": "Propriétés et nature",
  "세는 말": "Classificateurs et mots à compter",
  "소개하기(가족 소개)": "Présentation (Présenter sa famille)",
  "소개하기(자기소개)": "Présentation (Se présenter)",
  "소리": "Sons et bruits",
  "소통 수단": "Moyens de communication",
  "속도": "Vitesse",
  "수": "Nombres et chiffres",
  "순서": "Ordre et séquence",
  "스포츠": "Sports",
  "스포츠 전반": "Généralités sportives",
  "시간": "Temps et heure",
  "시간 표현하기": "Exprimer l'heure et la durée",
  "식문화": "Culture culinaire",
  "식물류": "Plantes et végétaux",
  "식물의 부분": "Parties de plantes",
  "식사 도구": "Ustensiles de table",
  "식사 및 조리 행위": "Prendre un repas et cuisiner",
  "식생활": "Alimentation",
  "식생활 관련 장소": "Lieux liés à l'alimentation",
  "식재료": "Ingrédients alimentaires",
  "신앙 대상": "Objets de culte et de foi",
  "신체 내부 구성": "Anatomie interne",
  "신체 변화": "Changements corporels",
  "신체 부위": "Parties du corps",
  "신체 행위": "Mouvements corporels",
  "신체에 가하는 행위": "Actions appliquées au corps",
  "실수담 말하기": "Raconter une bévue ou une erreur",
  "심리": "Psychologie",
  "약국 이용하기": "Aller à la pharmacie",
  "약속하기": "Prendre rendez-vous",
  "약품류": "Médicaments",
  "양": "Quantité",
  "언론": "Presse et journalisme",
  "언어": "Langue et langage",
  "언어 행위": "Actes de langage",
  "여가 도구": "Équipements de loisirs",
  "여가 생활": "Vie de loisirs",
  "여가 시설": "Installations de loisirs",
  "여가 활동": "Activités de loisirs",
  "여행": "Voyages",
  "역사": "Histoire",
  "연애와 결혼": "Amour et mariage",
  "영양": "Nutrition",
  "영화 보기": "Regarder des films",
  "예술": "Arts",
  "온도": "Température",
  "옷 종류": "Types de vêtements",
  "옷감": "Tissus et étoffes",
  "옷의 부분": "Parties de vêtements",
  "외모 표현하기": "Décrire l'apparence physique",
  "외양": "Apparence extérieure",
  "요리 설명하기": "Expliquer une recette de cuisine",
  "요일 표현하기": "Exprimer les jours de la semaine",
  "용모": "Traits du visage et physionomie",
  "위치 및 방향": "Position et direction",
  "위치 표현하기": "Exprimer la localisation",
  "음료": "Boissons",
  "음식": "Nourriture et plats",
  "음식 설명하기": "Décrire des plats",
  "음식 주문하기": "Commander à manger",
  "음악": "Musique",
  "의문": "Interrogation et doutes",
  "의복 착용 상태": "État vestimentaire",
  "의복 착용 행위": "Manière de s'habiller",
  "의생활": "Habillement",
  "의생활 관련 장소": "Lieux liés à l'habillement",
  "인간": "Êtres humains",
  "인간관계": "Relations humaines",
  "인사하기": "Saluer",
  "인지 행위": "Actes cognitifs",
  "인칭": "Personnes grammaticales",
  "일상 행위": "Actions du quotidien",
  "자연": "Nature",
  "자원": "Ressources naturelles",
  "재해": "Catastrophes",
  "전공과 교과목": "Matières et filières d'études",
  "전통 문화": "Culture traditionnelle",
  "전화하기": "Téléphoner",
  "접속": "Liaison et conjonction",
  "정도": "Degré et intensité",
  "정치": "Politique",
  "정치 및 치안 상태": "Conditions politiques et de sécurité",
  "정치 및 행정 주체": "Organes politiques et administratifs",
  "정치 및 행정 행위": "Actions politiques et administratives",
  "정치와 행정": "Politique et administration",
  "조리 도구": "Ustensiles de cuisine",
  "종교": "Religion",
  "종교 유형": "Types de religions",
  "종교 행위": "Pratiques religieuses",
  "종교 활동 도구": "Objets rituels",
  "종교 활동 장소": "Lieux de culte",
  "종교어": "Termes religieux",
  "종교인": "Religieux et membres du clergé",
  "주거 상태": "Conditions de logement",
  "주거 생활": "Vie résidentielle",
  "주거 지역": "Zones résidentielles",
  "주거 행위": "Habiter et se loger",
  "주거 형태": "Types d'habitat",
  "주말 및 휴가": "Week-ends et vacances",
  "주생활": "Habitat et logement",
  "주택 구성": "Composition du logement",
  "지리 정보": "Informations géographiques",
  "지시": "Désignation et repérage",
  "지역": "Régions et territoires",
  "지표면 사물": "Éléments à la surface de la Terre",
  "지형": "Relief et topographie",
  "직업": "Métiers et professions",
  "직업과 진로": "Métiers et orientation professionnelle",
  "직위": "Rangs et fonctions",
  "직장": "Lieu de travail",
  "직장 생활": "Vie professionnelle",
  "집 구하기": "Chercher un logement",
  "집안일": "Travaux ménagers",
  "채소": "Légumes",
  "천체": "Corps célestes",
  "철학·윤리": "Philosophie et éthique",
  "체력 상태": "Condition physique",
  "초대와 방문": "Invitations et visites",
  "취미": "Loisirs et passe-temps",
  "치료 시설": "Établissements de soins",
  "치료 행위": "Traitements médicaux",
  "친족 관계": "Relations de parenté",
  "컴퓨터와 인터넷": "Informatique et Internet",
  "태도": "Attitudes et comportements",
  "통신 행위": "Communications",
  "하루 생활": "Journée type",
  "학교 생활": "Vie scolaire",
  "학교 시설": "Installations scolaires",
  "학교생활": "Vie scolaire",
  "학문 용어": "Termes académiques",
  "학문 행위": "Travaux académiques",
  "학습 관련 사물": "Matériel scolaire",
  "한국 생활": "Vivre en Corée",
  "한국의 문학": "Littérature coréenne",
  "환경 문제": "Problèmes d'environnement"
}

ES_MAP = {
  "가사 행위": "Tareas del hogar",
  "가족 행사": "Eventos familiares",
  "가족 행사-명절": "Fiestas y celebraciones familiares",
  "감각": "Sentidos y sensaciones",
  "감사하기": "Agradecer",
  "감정": "Emociones",
  "감정, 기분 표현하기": "Expresar emociones y estado de ánimo",
  "개념": "Conceptos",
  "개인 정보 교환하기": "Intercambiar información personal",
  "건강": "Salud",
  "건물 종류": "Tipos de edificios",
  "건축": "Arquitectura",
  "경제 산물": "Productos económicos",
  "경제 상태": "Situación económica",
  "경제 생활": "Vida económica",
  "경제 수단": "Medios económicos",
  "경제 행위": "Actividades económicas",
  "경제 행위 장소": "Lugares de actividad económica",
  "경제 행위 주체": "Agentes económicos",
  "경제·경영": "Economía y administración",
  "곡류": "Cereales y granos",
  "곤충류": "Insectos",
  "공공 기관": "Instituciones públicas",
  "공공 기관 이용하기(도서관)": "Uso de instituciones públicas (Biblioteca)",
  "공공 기관 이용하기(우체국)": "Uso de instituciones públicas (Oficina de correos)",
  "공공 기관 이용하기(출입국 관리 사무소)": "Uso de instituciones públicas (Oficina de migración)",
  "공공기관 이용하기": "Uso de instituciones públicas",
  "공연과 감상": "Espectáculos y apreciación",
  "과일": "Frutas",
  "과학": "Ciencia",
  "과학 및 기술": "Ciencia y tecnología",
  "과학과 기술": "Ciencia y tecnología",
  "교수 학습 주체": "Participantes de enseñanza y aprendizaje",
  "교수 학습 행위": "Actividades de enseñanza y aprendizaje",
  "교육": "Educación",
  "교육 기관": "Instituciones educativas",
  "교통 수단": "Medios de transporte",
  "교통 이용 장소": "Lugares de transporte",
  "교통 이용 행위": "Uso del transporte",
  "교통 이용하기": "Usar el transporte",
  "기상 및 기후": "Meteorología y clima",
  "기후": "Clima",
  "길찾기": "Buscar direcciones",
  "날씨와 계절": "Clima y estaciones",
  "날짜 표현하기": "Expresar fechas",
  "능력": "Habilidades y capacidades",
  "대중 매체": "Medios de comunicación",
  "대중 문화": "Cultura popular",
  "동물 소리": "Sonidos de animales",
  "동물류": "Animales",
  "동물의 부분": "Partes de animales",
  "동식물": "Animales y plantas",
  "동식물 행위": "Conductas de animales y plantas",
  "말": "Habla y lenguaje",
  "맛": "Sabores",
  "매체": "Medios",
  "모양": "Formas y aspectos",
  "모자, 신발, 장신구": "Sombreros, calzado y accesorios",
  "무기": "Armas",
  "문제 해결하기(분실 및 고장)": "Resolución de problemas (Pérdidas y averías)",
  "문학": "Literatura",
  "문화": "Cultura",
  "문화 비교하기": "Comparar culturas",
  "문화 생활 장소": "Lugares de vida cultural",
  "문화 차이": "Diferencias culturales",
  "문화 활동": "Actividades culturales",
  "문화 활동 주체": "Actores de actividades culturales",
  "물건 사기": "Hacer compras",
  "미술": "Bellas artes",
  "미용 행위": "Cuidado estético y peluquería",
  "밝기": "Brillo y luminosidad",
  "법": "Derecho y leyes",
  "병과 증상": "Enfermedades y síntomas",
  "병원 이용하기": "Ir al hospital",
  "보건과 의료": "Salud y atención médica",
  "복장 표현하기": "Describir la vestimenta",
  "빈도": "Frecuencia",
  "사건, 사고, 재해 기술하기": "Describir incidentes, accidentes y desastres",
  "사과하기": "Disculparse",
  "사람의 종류": "Tipos de personas",
  "사법 및 치안 주체": "Autoridades judiciales y policiales",
  "사법 및 치안 행위": "Actos judiciales y de seguridad",
  "사회 문제": "Problemas sociales",
  "사회 생활": "Vida social",
  "사회 생활 상태": "Condición social",
  "사회 제도": "Sistemas sociales",
  "사회 행사": "Eventos sociales",
  "사회 활동": "Actividades sociales",
  "삶": "Vida",
  "삶의 상태": "Estados de vida",
  "삶의 행위": "Actos de la vida",
  "색깔": "Colores",
  "생리 현상": "Fenómenos fisiológicos",
  "생활 용품": "Artículos de uso cotidiano",
  "성격": "Personalidad",
  "성격 표현하기": "Describir la personalidad",
  "성질": "Propiedades y naturaleza",
  "세는 말": "Clasificadores numéricos",
  "소개하기(가족 소개)": "Presentaciones (Presentar a la familia)",
  "소개하기(자기소개)": "Presentaciones (Presentación personal)",
  "소리": "Sonidos",
  "소통 수단": "Medios de comunicación",
  "속도": "Velocidad",
  "수": "Números",
  "순서": "Orden y secuencia",
  "스포츠": "Deportes",
  "스포츠 전반": "Deportes en general",
  "시간": "Tiempo y horas",
  "시간 표현하기": "Expresar el tiempo y las horas",
  "식문화": "Cultura gastronómica",
  "식물류": "Plantas",
  "식물의 부분": "Partes de las plantas",
  "식사 도구": "Cubiertos y vajilla",
  "식사 및 조리 행위": "Comer y cocinar",
  "식생활": "Alimentación",
  "식생활 관련 장소": "Lugares relacionados con la comida",
  "식재료": "Ingredientes de cocina",
  "신앙 대상": "Objetos de fe",
  "신체 내부 구성": "Anatomía interna",
  "신체 변화": "Cambios corporales",
  "신체 부위": "Partes del cuerpo",
  "신체 행위": "Movimientos corporales",
  "신체에 가하는 행위": "Acciones aplicadas al cuerpo",
  "실수담 말하기": "Hablar de errores y tropiezos",
  "심리": "Psicología",
  "약국 이용하기": "Ir a la farmacia",
  "약속하기": "Concertar citas",
  "약품류": "Medicamentos",
  "양": "Cantidad",
  "언론": "Prensa y medios informativos",
  "언어": "Lengua e idiomas",
  "언어 행위": "Actos del lenguaje",
  "여가 도구": "Artículos de ocio",
  "여가 생활": "Tiempo libre y recreación",
  "여가 시설": "Instalaciones de ocio",
  "여가 활동": "Actividades recreativas",
  "여행": "Viajes",
  "역사": "Historia",
  "연애와 결혼": "Noviazgo y matrimonio",
  "영양": "Nutrición",
  "영화 보기": "Ver películas",
  "예술": "Arte",
  "온도": "Temperatura",
  "옷 종류": "Tipos de prendas",
  "옷감": "Tejidos y telas",
  "옷의 부분": "Partes de la ropa",
  "외모 표현하기": "Describir el aspecto físico",
  "외양": "Apariencia exterior",
  "요리 설명하기": "Explicar recetas y cocina",
  "요일 표현하기": "Expresar los días de la semana",
  "용모": "Facciones del rostro",
  "위치 및 방향": "Ubicación y orientación",
  "위치 표현하기": "Expresar ubicación",
  "음료": "Bebidas",
  "음식": "Comida y platos",
  "음식 설명하기": "Describir comidas",
  "음식 주문하기": "Pedir comida",
  "음악": "Música",
  "의문": "Dudas y preguntas",
  "의복 착용 상태": "Estado del atuendo",
  "의복 착용 행위": "Acción de vestirse",
  "의생활": "Indumentaria y vestimenta",
  "의생활 관련 장소": "Lugares de indumentaria",
  "인간": "Seres humanos",
  "인간관계": "Relaciones humanas",
  "인사하기": "Saludar",
  "인지 행위": "Actos cognitivos",
  "인칭": "Personas gramaticales",
  "일상 행위": "Acciones cotidianas",
  "자연": "Naturaleza",
  "자원": "Recursos naturales",
  "재해": "Desastres",
  "전공과 교과목": "Carreras y asignaturas",
  "전통 문화": "Cultura tradicional",
  "전화하기": "Hablar por teléfono",
  "접속": "Conectores y nexos",
  "정도": "Grado e intensidad",
  "정치": "Política",
  "정치 및 치안 상태": "Situación política y de seguridad",
  "정치 및 행정 주체": "Entidades políticas y administrativas",
  "정치 및 행정 행위": "Actos políticos y administrativos",
  "정치와 행정": "Política y administración",
  "조리 도구": "Utensilios de cocina",
  "종교": "Religión",
  "종교 유형": "Tipos de religiones",
  "종교 행위": "Prácticas religiosas",
  "종교 활동 도구": "Objetos de culto",
  "종교 활동 장소": "Lugares de culto",
  "종교어": "Léxico religioso",
  "종교인": "Religiosos y clérigos",
  "주거 상태": "Estado de la vivienda",
  "주거 생활": "Vida residencial",
  "주거 지역": "Zonas residenciales",
  "주거 행위": "Habitar y vivir",
  "주거 형태": "Tipos de vivienda",
  "주말 및 휴가": "Fines de semana y vacaciones",
  "주생활": "Vivienda y hogar",
  "주택 구성": "Distribución de la vivienda",
  "지리 정보": "Información geográfica",
  "지시": "Deixis e indicaciones",
  "지역": "Regiones y zonas",
  "지표면 사물": "Elementos de la superficie terrestre",
  "지형": "Relieve y topografía",
  "직업": "Profesiones y oficios",
  "직업과 진로": "Trabajo y orientación laboral",
  "직위": "Cargos y puestos",
  "직장": "Lugar de trabajo",
  "직장 생활": "Vida laboral",
  "집 구하기": "Buscar casa",
  "집안일": "Quehaceres domésticos",
  "채소": "Verduras y hortalizas",
  "천체": "Cuerpos celestes",
  "철학·윤리": "Filosofía y ética",
  "체력 상태": "Condición física",
  "초대와 방문": "Invitaciones y visitas",
  "취미": "Pasatiempos",
  "치료 시설": "Instalaciones médicas",
  "치료 행위": "Tratamientos médicos",
  "친족 관계": "Parentesco familiar",
  "컴퓨터와 인터넷": "Computadoras e Internet",
  "태도": "Actitud",
  "통신 행위": "Comunicaciones",
  "하루 생활": "Rutina diaria",
  "학교 생활": "Vida escolar",
  "학교 시설": "Instalaciones escolares",
  "학교생활": "Vida escolar",
  "학문 용어": "Términos académicos",
  "학문 행위": "Actividades académicas",
  "학습 관련 사물": "Material de estudio",
  "한국 생활": "Vivir en Corea",
  "한국의 문학": "Literatura coreana",
  "환경 문제": "Problemas medioambientales"
}

RU_MAP = {
  "가사 행위": "Домашние дела",
  "가족 행사": "Семейные праздники",
  "가족 행사-명절": "Семейные праздники и знаменательные дни",
  "감각": "Ощущения и чувства",
  "감사하기": "Выражение благодарности",
  "감정": "Эмоции",
  "감정, 기분 표현하기": "Выражение эмоций и настроения",
  "개념": "Понятия",
  "개인 정보 교환하기": "Обмен личными данными",
  "건강": "Здоровье",
  "건물 종류": "Виды зданий",
  "건축": "Архитектура",
  "경제 산물": "Экономическая продукция",
  "경제 상태": "Экономическое состояние",
  "경제 생활": "Экономическая жизнь",
  "경제 수단": "Экономические средства",
  "경제 행위": "Экономическая деятельность",
  "경제 행위 장소": "Места экономической деятельности",
  "경제 행위 주체": "Субъекты экономики",
  "경제·경영": "Экономика и менеджмент",
  "곡류": "Зерновые культуры",
  "곤충류": "Насекомые",
  "공공 기관": "Государственные учреждения",
  "공공 기관 이용하기(도서관)": "Посещение учреждений (Библиотека)",
  "공공 기관 이용하기(우체국)": "Посещение учреждений (Почта)",
  "공공 기관 이용하기(출입국 관리 사무소)": "Посещение учреждений (Иммиграционная служба)",
  "공공기관 이용하기": "Посещение общественных учреждений",
  "공연과 감상": "Концерты и представления",
  "과일": "Фрукты",
  "과학": "Наука",
  "과학 및 기술": "Наука и технологии",
  "과학과 기술": "Наука и техника",
  "교수 학습 주체": "Субъекты учебного процесса",
  "교수 학습 행위": "Учебно-воспитательная деятельность",
  "교육": "Образование",
  "교육 기관": "Учебные заведения",
  "교통 수단": "Транспортные средства",
  "교통 이용 장소": "Транспортные пункты",
  "교통 이용 행위": "Поездки на транспорте",
  "교통 이용하기": "Пользование транспортом",
  "기상 및 기후": "Погода и климат",
  "기후": "Климат",
  "길찾기": "Ориентирование на местности",
  "날씨와 계절": "Погода и времена года",
  "날짜 표현하기": "Выражение дат",
  "능력": "Способности и навыки",
  "대중 매체": "Средства массовой информации",
  "대중 문화": "Популярная культура",
  "동물 소리": "Звуки животных",
  "동물류": "Животные",
  "동물의 부분": "Части тела животных",
  "동식물": "Флора и фауна",
  "동식물 행위": "Поведение животных и растений",
  "말": "Речь и язык",
  "맛": "Вкусы",
  "매체": "СМИ и медиа",
  "모양": "Форма и вид",
  "모자, 신발, 장신구": "Головные уборы, обувь и украшения",
  "무기": "Оружие",
  "문제 해결하기(분실 및 고장)": "Решение проблем (Утеря и поломка)",
  "문학": "Литература",
  "문화": "Культура",
  "문화 비교하기": "Сравнение культур",
  "문화 생활 장소": "Места культурного досуга",
  "문화 차이": "Культурные различия",
  "문화 활동": "Культурная деятельность",
  "문화 활동 주체": "Деятели культуры",
  "물건 사기": "Покупка товаров",
  "미술": "Изобразительное искусство",
  "미용 행위": "Косметический уход",
  "밝기": "Яркость и освещение",
  "법": "Право и закон",
  "병과 증상": "Болезни и симптомы",
  "병원 이용하기": "Визит к врачу",
  "보건과 의료": "Здравоохранение и медицина",
  "복장 표현하기": "Описание одежды",
  "빈도": "Частота и периодичность",
  "사건, 사고, 재해 기술하기": "Описание происшествий и бедствий",
  "사과하기": "Извинения",
  "사람의 종류": "Категории людей",
  "사법 및 치안 주체": "Судебные и правоохранительные органы",
  "사법 및 치안 행위": "Охрана правопорядка",
  "사회 문제": "Социальные проблемы",
  "사회 생활": "Общественная жизнь",
  "사회 생활 상태": "Социальное положение",
  "사회 제도": "Общественные институты",
  "사회 행사": "Общественные события",
  "사회 활동": "Общественная деятельность",
  "삶": "Жизнь",
  "삶의 상태": "Условия жизни",
  "삶의 행위": "Жизненные поступки",
  "색깔": "Цвета",
  "생리 현상": "Физиологические процессы",
  "생활 용품": "Предметы обихода",
  "성격": "Характер",
  "성격 표현하기": "Описание характера",
  "성질": "Свойства и качества",
  "세는 말": "Счётные слова",
  "소개하기(가족 소개)": "Знакомство (О семье)",
  "소개하기(자기소개)": "Знакомство (О себе)",
  "소리": "Звуки",
  "소통 수단": "Средства коммуникации",
  "속도": "Скорость",
  "수": "Числа",
  "순서": "Порядок и очерёдность",
  "스포츠": "Спорт",
  "스포츠 전반": "Спорт в целом",
  "시간": "Время",
  "시간 표현하기": "Выражение времени",
  "식문화": "Культура питания",
  "식물류": "Растения",
  "식물의 부분": "Части растений",
  "식사 도구": "Столовые приборы",
  "식사 및 조리 행위": "Приём и приготовление пищи",
  "식생활": "Питание",
  "식생활 관련 장소": "Места общепита",
  "식재료": "Пищевые ингредиенты",
  "신앙 대상": "Объекты почитания",
  "신체 내부 구성": "Внутренние органы",
  "신체 변화": "Изменения в теле",
  "신체 부위": "Части тела",
  "신체 행위": "Движения тела",
  "신체에 가하는 행위": "Воздействия на тело",
  "실수담 말하기": "Рассказ об оплошностях",
  "심리": "Психология",
  "약국 이용하기": "Посещение аптеки",
  "약속하기": "Договоренности о встрече",
  "약품류": "Лекарственные средства",
  "양": "Количество",
  "언론": "Пресса и журналистика",
  "언어": "Язык и речь",
  "언어 행위": "Речевые акты",
  "여가 도구": "Инвентарь для отдыха",
  "여가 생활": "Досуг и отдых",
  "여가 시설": "Места отдыха",
  "여가 활동": "Проведение досуга",
  "여행": "Путешествия",
  "역사": "История",
  "연애와 결혼": "Отношения и брак",
  "영양": "Питание и нутриенты",
  "영화 보기": "Просмотр фильмов",
  "예술": "Искусство",
  "온도": "Температура",
  "옷 종류": "Виды одежды",
  "옷감": "Ткани",
  "옷의 부분": "Детали одежды",
  "외모 표현하기": "Описание внешности",
  "외양": "Внешний облик",
  "요리 설명하기": "Объяснение рецептов",
  "요일 표현하기": "Дни недели",
  "용모": "Черты лица",
  "위치 및 방향": "Расположение и направление",
  "위치 표현하기": "Указание места",
  "음료": "Напитки",
  "음식": "Еда и блюда",
  "음식 설명하기": "Описание блюд",
  "음식 주문하기": "Заказ еды",
  "음악": "Музыка",
  "의문": "Вопросы и сомнения",
  "의복 착용 상태": "Состояние одежды",
  "의복 착용 행위": "Процесс одевания",
  "의생활": "Одежда и стиль",
  "의생활 관련 장소": "Магазины одежды и ателье",
  "인간": "Человек",
  "인간관계": "Отношения между людьми",
  "인사하기": "Приветствие",
  "인지 행위": "Познавательная деятельность",
  "인칭": "Грамматические лица",
  "일상 행위": "Повседневные дела",
  "자연": "Природа",
  "자원": "Природные ресурсы",
  "재해": "Стихийные бедствия",
  "전공과 교과목": "Специальности и предметы",
  "전통 문화": "Традиционная культура",
  "전화하기": "Разговор по телефону",
  "접속": "Союзы и связки",
  "정도": "Степень и мера",
  "정치": "Политика",
  "정치 및 치안 상태": "Политика и безопасность",
  "정치 및 행정 주체": "Государственные органы",
  "정치 및 행정 행위": "Административная деятельность",
  "정치와 행정": "Политика и управление",
  "조리 도구": "Кухонные принадлежности",
  "종교": "Религия",
  "종교 유형": "Конфессии и верования",
  "종교 행위": "Религиозные обряды",
  "종교 활동 도구": "Предметы культа",
  "종교 활동 장소": "Культовые сооружения",
  "종교어": "Религиозная лексика",
  "종교인": "Священнослужители",
  "주거 상태": "Жилищные условия",
  "주거 생활": "Быт и проживание",
  "주거 지역": "Жилые районы",
  "주거 행위": "Проживание",
  "주거 형태": "Виды жилья",
  "주말 및 휴가": "Выходные и отпуск",
  "주생활": "Быт и жильё",
  "주택 구성": "Планировка жилья",
  "지리 정보": "География",
  "지시": "Указательные слова",
  "지역": "Регионы",
  "지표면 사물": "Объекты земной поверхности",
  "지형": "Рельеф местности",
  "직업": "Профессии",
  "직업과 진로": "Карьера и профориентация",
  "직위": "Должности и звания",
  "직장": "Место работы",
  "직장 생활": "Трудовые будни",
  "집 구하기": "Поиск жилья",
  "집안일": "Домашнее хозяйство",
  "채소": "Овощи",
  "천체": "Небесные тела",
  "철학·윤리": "Философия и этика",
  "체력 상태": "Физическая форма",
  "초대와 방문": "Визиты и приём гостей",
  "취미": "Увлечения",
  "치료 시설": "Лечебные заведения",
  "치료 행위": "Медицинские процедуры",
  "친족 관계": "Родственные связи",
  "컴퓨터와 인터넷": "Компьютеры и интернет",
  "태도": "Отношение и поведение",
  "통신 행위": "Связь и телекоммуникации",
  "하루 생활": "Распорядок дня",
  "학교 생활": "Школьная жизнь",
  "학교 시설": "Школьные помещения",
  "학교생활": "Учёба в школе",
  "학문 용어": "Научная терминология",
  "학문 행위": "Научные исследования",
  "학습 관련 사물": "Учебные принадлежности",
  "한국 생활": "Жизнь в Корее",
  "한국의 문학": "Корейская литература",
  "환경 문제": "Экология"
}
