# -*- coding: utf-8 -*-
"""
Language mappings for Vietnamese (vi), Mongolian (mn), Arabic (ar), Thai (th), Indonesian (id)
for all 232 category components.
"""

VI_MAP = {
  "가사 행위": "Việc nhà", "가족 행사": "Sự kiện gia đình", "가족 행사-명절": "Lễ tết gia đình", "감각": "Giác quan",
  "감사하기": "Bày tỏ cảm ơn", "감정": "Tình cảm", "감정, 기분 표현하기": "Bày tỏ cảm xúc, tâm trạng", "개념": "Khái niệm",
  "개인 정보 교환하기": "Trao đổi thông tin cá nhân", "건강": "Sức khỏe", "건물 종류": "Các loại công trình", "건축": "Kiến trúc",
  "경제 산물": "Sản phẩm kinh tế", "경제 상태": "Tình trạng kinh tế", "경제 생활": "Đời sống kinh tế", "경제 수단": "Phương tiện kinh tế",
  "경제 행위": "Hoạt động kinh tế", "경제 행위 장소": "Địa điểm hoạt động kinh tế", "경제 행위 주체": "Chủ thể hoạt động kinh tế", "경제·경영": "Kinh tế - Kinh doanh",
  "곡류": "Ngũ cốc", "곤충류": "Côn trùng", "공공 기관": "Cơ quan công cộng", "공공 기관 이용하기(도서관)": "Sử dụng cơ quan công cộng (Thư viện)",
  "공공 기관 이용하기(우체국)": "Sử dụng cơ quan công cộng (Bưu điện)", "공공 기관 이용하기(출입국 관리 사무소)": "Sử dụng cơ quan công cộng (Cục xuất nhập cảnh)",
  "공공기관 이용하기": "Sử dụng cơ quan công cộng", "공연과 감상": "Biểu diễn và thưởng thức", "과일": "Hoa quả", "과학": "Khoa học",
  "과학 및 기술": "Khoa học và công nghệ", "과학과 기술": "Khoa học và kỹ thuật", "교수 학습 주체": "Chủ thể dạy và học",
  "교수 학습 행위": "Hoạt động dạy và học", "교육": "Giáo dục", "교육 기관": "Cơ quan giáo dục", "교통 수단": "Phương tiện giao thông",
  "교통 이용 장소": "Địa điểm giao thông", "교통 이용 행위": "Hành vi sử dụng giao thông", "교통 이용하기": "Sử dụng giao thông",
  "기상 및 기후": "Khí tượng và khí hậu", "기후": "Khí hậu", "길찾기": "Tìm đường", "날씨와 계절": "Thời tiết và các mùa",
  "날짜 표현하기": "Diễn đạt ngày tháng", "능력": "Năng lực", "대중 매체": "Phương tiện truyền thông đại chúng", "대중 문화": "Văn hóa đại chúng",
  "동물 소리": "Tiếng kêu động vật", "동물류": "Động vật", "동물의 부분": "Bộ phận động vật", "동식물": "Động thực vật",
  "동식물 행위": "Hành vi động thực vật", "말": "Lời nói và ngôn ngữ", "맛": "Hương vị", "매체": "Phương tiện truyền thông",
  "모양": "Hình dạng", "모자, 신발, 장신구": "Mũ, giày dép, phụ kiện", "무기": "Vũ khí", "문제 해결하기(분실 및 고장)": "Giải quyết sự cố (Mất đồ và hỏng hóc)",
  "문학": "Văn học", "문화": "Văn hóa", "문화 비교하기": "So sánh văn hóa", "문화 생활 장소": "Địa điểm sinh hoạt văn hóa",
  "문화 차이": "Sự khác biệt văn hóa", "문화 활동": "Hoạt động văn hóa", "문화 활동 주체": "Chủ thể hoạt động văn hóa", "물건 사기": "Mua sắm",
  "미술": "Mỹ thuật", "미용 행위": "Chăm sóc sắc đẹp", "밝기": "Độ sáng", "법": "Pháp luật", "병과 증상": "Bệnh tật và triệu chứng",
  "병원 이용하기": "Khám bệnh tại bệnh viện", "보건과 의료": "Y tế và sức khỏe", "복장 표현하기": "Diễn tả trang phục", "빈도": "Tần suất",
  "사건, 사고, 재해 기술하기": "Mô tả sự cố, tai nạn, thiên tai", "사과하기": "Xin lỗi", "사람의 종류": "Các kiểu người",
  "사법 및 치안 주체": "Cơ quan tư pháp và trị an", "사법 및 치안 행위": "Hành vi tư pháp và trị an", "사회 문제": "Vấn đề xã hội",
  "사회 생활": "Đời sống xã hội", "사회 생활 상태": "Tình trạng đời sống xã hội", "사회 제도": "Thể chế xã hội", "사회 행사": "Sự kiện xã hội",
  "사회 활동": "Hoạt động xã hội", "삶": "Cuộc sống", "삶의 상태": "Trạng thái cuộc sống", "삶의 행위": "Hành vi cuộc sống",
  "색깔": "Màu sắc", "생리 현상": "Hiện tượng sinh lý", "생활 용품": "Đồ dùng sinh hoạt", "성격": "Tính cách", "성격 표현하기": "Miêu tả tính cách",
  "성질": "Tính chất", "세는 말": "Từ chỉ số lượng (Lượng từ)", "소개하기(가족 소개)": "Giới thiệu (Giới thiệu gia đình)",
  "소개하기(자기소개)": "Giới thiệu (Tự giới thiệu)", "소리": "Âm thanh", "소통 수단": "Phương tiện giao tiếp", "속도": "Tốc độ",
  "수": "Số đếm", "순서": "Thứ tự", "스포츠": "Thể thao", "스포츠 전반": "Thể thao tổng hợp", "시간": "Thời gian",
  "시간 표현하기": "Diễn đạt thời gian", "식문화": "Văn hóa ẩm thực", "식물류": "Thực vật", "식물의 부분": "Bộ phận thực vật",
  "식사 도구": "Dụng cụ ăn uống", "식사 및 조리 행위": "Ăn uống và nấu nướng", "식생활": "Đời sống ăn uống", "식생활 관련 장소": "Địa điểm ăn uống",
  "식재료": "Nguyên liệu thực phẩm", "신앙 대상": "Đối tượng tín ngưỡng", "신체 내부 구성": "Cơ quan nội tạng", "신체 변화": "Biến đổi cơ thể",
  "신체 부위": "Bộ phận cơ thể", "신체 행위": "Cử động cơ thể", "신체에 가하는 행위": "Tác động lên cơ thể", "실수담 말하기": "Kể về lỗi lầm",
  "심리": "Tâm lý", "약국 이용하기": "Đến hiệu thuốc", "약속하기": "Hẹn gặp", "약품류": "Dược phẩm", "양": "Số lượng",
  "언론": "Báo chí", "언어": "Ngôn ngữ", "언어 행위": "Hành vi ngôn ngữ", "여가 도구": "Dụng cụ giải trí", "여가 생활": "Đời sống giải trí",
  "여가 시설": "Cơ sở giải trí", "여가 활동": "Hoạt động giải trí", "여행": "Du lịch", "역사": "Lịch sử", "연애와 결혼": "Tình yêu và hôn nhân",
  "영양": "Dinh dưỡng", "영화 보기": "Xem phim", "예술": "Nghệ thuật", "온도": "Nhiệt độ", "옷 종류": "Các loại trang phục",
  "옷감": "Vải vóc", "옷의 부분": "Bộ phận quần áo", "외모 표현하기": "Miêu tả ngoại hình", "외양": "Diện mạo bên ngoài",
  "요리 설명하기": "Hướng dẫn nấu ăn", "요일 표현하기": "Diễn đạt thứ trong tuần", "용모": "Diện mạo", "위치 및 방향": "Vị trí và phương hướng",
  "위치 표현하기": "Diễn đạt vị trí", "음료": "Đồ uống", "음식": "Thức ăn", "음식 설명하기": "Giới thiệu món ăn", "음식 주문하기": "Gọi món ăn",
  "음악": "Âm nhạc", "의문": "Nghi vấn", "의복 착용 상태": "Tình trạng mặc trang phục", "의복 착용 행위": "Hành vi mặc trang phục",
  "의생활": "Đời sống trang phục", "의생활 관련 장소": "Địa điểm liên quan trang phục", "인간": "Con người", "인간관계": "Quan hệ con người",
  "인사하기": "Chào hỏi", "인지 행위": "Hành vi nhận thức", "인칭": "Ngôi xưng hô", "일상 행위": "Hành động hàng ngày",
  "자연": "Tự nhiên", "자원": "Tài nguyên", "재해": "Thiên tai", "전공과 교과목": "Chuyên ngành và môn học", "전통 문화": "Văn hóa truyền thống",
  "전화하기": "Gọi điện thoại", "접속": "Liên từ nối", "정도": "Mức độ", "정치": "Chính trị", "정치 및 치안 상태": "Tình hình chính trị và trị an",
  "정치 및 행정 주체": "Cơ quan chính trị và hành chính", "정치 및 행정 행위": "Hoạt động chính trị và hành chính", "정치와 행정": "Chính trị và hành chính",
  "조리 도구": "Dụng cụ nấu nướng", "종교": "Tôn giáo", "종교 유형": "Các loại tôn giáo", "종교 행위": "Nghi lễ tôn giáo",
  "종교 활동 도구": "Dụng cụ tôn giáo", "종교 활동 장소": "Địa điểm tôn giáo", "종교어": "Từ ngữ tôn giáo", "종교인": "Người theo đạo",
  "주거 상태": "Tình trạng nhà ở", "주거 생활": "Đời sống cư trú", "주거 지역": "Khu dân cư", "주거 행위": "Hành vi sinh sống",
  "주거 형태": "Hình thức nhà ở", "주말 및 휴가": "Cuối tuần và kỳ nghỉ", "주생활": "Đời sống nhà ở", "주택 구성": "Cấu trúc nhà ở",
  "지리 정보": "Thông tin địa lý", "지시": "Chỉ định", "지역": "Khu vực", "지표면 사물": "Sự vật trên mặt đất", "지형": "Địa hình",
  "직업": "Nghề nghiệp", "직업과 진로": "Nghề nghiệp và định hướng", "직위": "Chức vụ", "직장": "Nơi làm việc", "직장 생활": "Đời sống công sở",
  "집 구하기": "Tìm nhà", "집안일": "Công việc trong nhà", "채소": "Rau củ", "천체": "Thiên thể", "철학·윤리": "Triết học và đạo đức",
  "체력 상태": "Thể lực", "초대와 방문": "Mời và thăm hỏi", "취미": "Sở thích", "치료 시설": "Cơ sở điều trị", "치료 행위": "Hành vi điều trị",
  "친족 관계": "Quan hệ họ hàng", "컴퓨터와 인터넷": "Máy tính và Internet", "태도": "Thái độ", "통신 행위": "Hành vi liên lạc",
  "하루 생활": "Sinh hoạt thường ngày", "학교 생활": "Đời sống học đường", "학교 시설": "Cơ sở vật chất trường học", "학교생활": "Đời sống học đường",
  "학문 용어": "Thuật ngữ học thuật", "학문 행위": "Hoạt động học thuật", "학습 관련 사물": "Đồ dùng học tập", "한국 생활": "Cuộc sống ở Hàn Quốc",
  "한국의 문학": "Văn học Hàn Quốc", "환경 문제": "Vấn đề môi trường"
}

ID_MAP = {
  "가사 행위": "Pekerjaan rumah tangga", "가족 행사": "Acara keluarga", "가족 행사-명절": "Perayaan keluarga dan hari libur",
  "감각": "Indra dan sensasi", "감사하기": "Mengungkapkan terima kasih", "감정": "Emosi", "감정, 기분 표현하기": "Mengekspresikan emosi dan suasana hati",
  "개념": "Konsep", "개인 정보 교환하기": "Bertukar informasi pribadi", "건강": "Kesehatan", "건물 종류": "Jenis bangunan",
  "건축": "Arsitektur", "경제 산물": "Produk ekonomi", "경제 상태": "Kondisi ekonomi", "경제 생활": "Kehidupan ekonomi",
  "경제 수단": "Sarana ekonomi", "경제 행위": "Aktivitas ekonomi", "경제 행위 장소": "Tempat aktivitas ekonomi",
  "경제 행위 주체": "Pelaku ekonomi", "경제·경영": "Ekonomi dan manajemen", "곡류": "Biji-bijian", "곤충류": "Serangga",
  "공공 기관": "Lembaga publik", "공공 기관 이용하기(도서관)": "Menggunakan fasilitas umum (Perpustakaan)",
  "공공 기관 이용하기(우체국)": "Menggunakan fasilitas umum (Kantor pos)",
  "공공 기관 이용하기(출입국 관리 사무소)": "Menggunakan fasilitas umum (Kantor imigrasi)",
  "공공기관 이용하기": "Menggunakan fasilitas umum", "공연과 감상": "Pertunjukan dan apresiasi", "과일": "Buah-buahan",
  "과학": "Sains", "과학 및 기술": "Sains dan teknologi", "과학과 기술": "Sains dan teknologi",
  "교수 학습 주체": "Subjek belajar-mengajar", "교수 학습 행위": "Aktivitas belajar-mengajar", "교육": "Pendidikan",
  "교육 기관": "Lembaga pendidikan", "교통 수단": "Moda transportasi", "교통 이용 장소": "Tempat transportasi",
  "교통 이용 행위": "Aktivitas menggunakan transportasi", "교통 이용하기": "Menggunakan transportasi",
  "기상 및 기후": "Cuaca dan iklim", "기후": "Iklim", "길찾기": "Menemukan jalan", "날씨와 계절": "Cuaca dan musim",
  "날짜 표현하기": "Menyatakan tanggal", "능력": "Kemampuan", "대중 매체": "Media massa", "대중 문화": "Budaya populer",
  "동물 소리": "Suara hewan", "동물류": "Hewan", "동물의 부분": "Bagian tubuh hewan", "동식물": "Flora dan fauna",
  "동식물 행위": "Perilaku hewan dan tumbuhan", "말": "Ujaran dan bahasa", "맛": "Rasa", "매체": "Media",
  "모양": "Bentuk dan rupa", "모자, 신발, 장신구": "Topi, sepatu, aksesori", "무기": "Senjata",
  "문제 해결하기(분실 및 고장)": "Pemecahan masalah (Kehilangan dan kerusakan)", "문학": "Sastra", "문화": "Budaya",
  "문화 비교하기": "Membandingkan budaya", "문화 생활 장소": "Tempat kegiatan budaya", "문화 차이": "Perbedaan budaya",
  "문화 활동": "Aktivitas budaya", "문화 활동 주체": "Pelaku aktivitas budaya", "물건 사기": "Berbelanja", "미술": "Seni rupa",
  "미용 행위": "Perawatan kecantikan", "밝기": "Kecerahan", "법": "Hukum", "병과 증상": "Penyakit dan gejala",
  "병원 이용하기": "Berobat ke rumah sakit", "보건과 의료": "Kesehatan dan medis", "복장 표현하기": "Mendeskripsikan pakaian",
  "빈도": "Frekuensi", "사건, 사고, 재해 기술하기": "Menceritakan insiden, kecelakaan, bencana", "사과하기": "Meminta maaf",
  "사람의 종류": "Tipe-tipe orang", "사법 및 치안 주체": "Penegak hukum dan keamanan",
  "사법 및 치안 행위": "Tindakan hukum dan ketertiban", "사회 문제": "Masalah sosial", "사회 생활": "Kehidupan sosial",
  "사회 생활 상태": "Kondisi kehidupan sosial", "사회 제도": "Sistem sosial", "사회 행사": "Acara sosial",
  "사회 활동": "Aktivitas sosial", "삶": "Kehidupan", "삶의 상태": "Kondisi kehidupan", "삶의 행위": "Tindakan kehidupan",
  "색깔": "Warna", "생리 현상": "Gejala fisiologis", "생활 용품": "Barang kebutuhan sehari-hari", "성격": "Kepribadian",
  "성격 표현하기": "Mendeskripsikan kepribadian", "성질": "Sifat dan karakteristik", "세는 말": "Kata bantu bilangan",
  "소개하기(가족 소개)": "Perkenalan (Mengenalkan keluarga)", "소개하기(자기소개)": "Perkenalan (Perkenalan diri)",
  "소리": "Suara", "소통 수단": "Sarana komunikasi", "속도": "Kecepatan", "수": "Angka", "순서": "Urutan",
  "스포츠": "Olahraga", "스포츠 전반": "Olahraga secara umum", "시간": "Waktu", "시간 표현하기": "Menyatakan waktu",
  "식문화": "Budaya makan", "식물류": "Tumbuhan", "식물의 부분": "Bagian tumbuhan", "식사 도구": "Alat makan",
  "식사 및 조리 행위": "Makan dan memasak", "식생활": "Kehidupan bersantap", "식생활 관련 장소": "Tempat bersantap",
  "식재료": "Bahan makanan", "신앙 대상": "Objek keyakinan", "신체 내부 구성": "Organ dalam tubuh", "신체 변화": "Perubahan fisik",
  "신체 부위": "Bagian tubuh", "신체 행위": "Gerakan tubuh", "신체에 가하는 행위": "Tindakan pada tubuh",
  "실수담 말하기": "Menceritakan kekeliruan", "심리": "Psikologi", "약국 이용하기": "Pergi ke apotek", "약속하기": "Membuat janji",
  "약품류": "Obat-obatan", "양": "Kuantitas", "언론": "Pers", "언어": "Bahasa", "언어 행위": "Tindakan berbahasa",
  "여가 도구": "Peralatan rekreasi", "여가 생활": "Kehidupan santai", "여가 시설": "Fasilitas rekreasi",
  "여가 활동": "Aktivitas rekreasi", "여행": "Perjalanan", "역사": "Sejarah", "연애와 결혼": "Percintaan dan pernikahan",
  "영양": "Nutrisi", "영화 보기": "Menonton film", "예술": "Seni", "온도": "Suhu", "옷 종류": "Jenis pakaian",
  "옷감": "Bahan kain", "옷의 부분": "Bagian pakaian", "외모 표현하기": "Mendeskripsikan penampilan luar",
  "외양": "Rupa lahiriah", "요리 설명하기": "Menjelaskan resep masakan", "요일 표현하기": "Menyatakan hari dalam seminggu",
  "용모": "Raut wajah", "위치 및 방향": "Lokasi dan arah", "위치 표현하기": "Menyatakan lokasi", "음료": "Minuman",
  "음식": "Makanan", "음식 설명하기": "Mendeskripsikan makanan", "음식 주문하기": "Memesan makanan", "음악": "Musik",
  "의문": "Pertanyaan dan keraguan", "의복 착용 상태": "Kondisi berbusana", "의복 착용 행위": "Tindakan berpakaian",
  "의생활": "Kehidupan berbusana", "의생활 관련 장소": "Tempat terkait pakaian", "인간": "Manusia",
  "인간관계": "Hubungan antarmanusia", "인사하기": "Memberi salam", "인지 행위": "Aktivitas kognitif",
  "인칭": "Pronomina persona", "일상 행위": "Aktivitas sehari-hari", "자연": "Alam", "자원": "Sumber daya",
  "재해": "Bencana", "전공과 교과목": "Jurusan dan mata pelajaran", "전통 문화": "Budaya tradisional",
  "전화하기": "Menelepon", "접속": "Konjungsi penghubung", "정도": "Tingkat dan derajat", "정치": "Politik",
  "정치 및 치안 상태": "Kondisi politik dan keamanan", "정치 및 행정 주체": "Badan politik dan administratif",
  "정치 및 행정 행위": "Tindakan politik dan administrasi", "정치와 행정": "Politik dan administrasi",
  "조리 도구": "Peralatan masak", "종교": "Agama", "종교 유형": "Jenis agama", "종교 행위": "Praktik keagamaan",
  "종교 활동 도구": "Perlengkapan ritual keagamaan", "종교 활동 장소": "Tempat ibadah", "종교어": "Istilah keagamaan",
  "종교인": "Pemuka agama", "주거 상태": "Kondisi tempat tinggal", "주거 생활": "Kehidupan tempat tinggal",
  "주거 지역": "Kawasan perumahan", "주거 행위": "Aktivitas bertempat tinggal", "주거 형태": "Tipe hunian",
  "주말 및 휴가": "Akhir pekan dan liburan", "주생활": "Kehidupan perumahan", "주택 구성": "Struktur rumah",
  "지리 정보": "Informasi geografis", "지시": "Petunjuk dan deiksis", "지역": "Daerah dan wilayah",
  "지표면 사물": "Objek permukaan tanah", "지형": "Topografi", "직업": "Pekerjaan", "직업과 진로": "Pekerjaan dan masa depan",
  "직위": "Jabatan", "직장": "Tempat kerja", "직장 생활": "Kehidupan kerja", "집 구하기": "Mencari rumah",
  "집안일": "Urusan rumah tangga", "채소": "Sayuran", "천체": "Benda langit", "철학·윤리": "Filsafat dan etika",
  "체력 상태": "Kebugaran fisik", "초대와 방문": "Undangan dan kunjungan", "취미": "Hobi",
  "치료 시설": "Fasilitas perawatan medis", "치료 행위": "Tindakan pengobatan", "친족 관계": "Hubungan kekerabatan",
  "컴퓨터와 인터넷": "Komputer dan internet", "태도": "Sikap", "통신 행위": "Aktivitas telekomunikasi",
  "하루 생활": "Keseharian", "학교 생활": "Kehidupan sekolah", "학교 시설": "Fasilitas sekolah", "학교생활": "Kehidupan sekolah",
  "학문 용어": "Istilah akademik", "학문 행위": "Kegiatan akademik", "학습 관련 사물": "Perlengkapan belajar",
  "한국 생활": "Kehidupan di Korea", "한국의 문학": "Sastra Korea", "환경 문제": "Masalah lingkungan"
}
